name: Android iOS CI

on: 
  workflow_dispatch: {}
  
jobs:

  testRunner:
   name: Test Edit Mode
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Cache library
       uses: actions/cache@v2
       with:
        path: Library
        key: Library-${{ matrix.targetPlatform }}
        restore-keys: Library-

     - uses: game-ci/unity-test-runner@v2
       env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
       with:
        testMode: EditMode

  build:
    needs: testRunner
    name: Builds
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android
          - iOS
        unityVersion:
          - 2021.1.21f1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Cache library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.targetPlatform }})
          path: build/${{ matrix.targetPlatform }}
